#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#小明身高1.75，体重80.5kg。请根据BMI公式（体重除以身高的平方）帮小明计算他的BMI指数，并根据BMI指数：
#低于18.5：过轻
#18.5-25：正常
#25-28：过重
#28-32：肥胖
#高于32：严重肥胖
Hi = input('How tall are you ? (米，eg:1.65)')
We = input('What is your weight (千克,eg:80.5)? ')
H=float(Hi)
W=float(We)
bmi=(W/(H**2))
while True:
    if bmi<18.5 and bmi>0:
       print('Your BMI is :','过轻')
       break
    elif bmi>=18.5 and bmi< 25:
       print('Your BMI is :','正常')
       break
    elif bmi>=25 and bmi< 28:
       print('Your BMI is :','过重')
       break
    elif bmi>=28 and bmi< 32:
       print('Your BMI is :','肥胖')
       break
    else:
       print('Your BMI is :','过重')
       break
